services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio-local
    restart: always
    networks:
      - chatbot
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_IDENTITY_PLUGIN_URL: "http://host.docker.internal:3000/auth"
      MINIO_IDENTITY_PLUGIN_ROLE_POLICY: "consoleAdmin"
      MINIO_IDENTITY_PLUGIN_ROLE_ID: "mobile-app"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

networks:
  chatbot:
    driver: bridge
volumes:
  minio-data:
